# Generated by Django 3.2 on 2021-04-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_moodle_uv', '0002_dacademicperiods'),
    ]

    operations = [
        migrations.CreateModel(
            name='DResource',
            fields=[
                ('technical_surrogate_key_field', models.BigAutoField(db_column='technical/surrogate key field', primary_key=True, serialize=False, unique=True)),
                ('id_moodle', models.IntegerField(blank=True, null=True)),
                ('activityname', models.CharField(blank=True, max_length=500, null=True)),
                ('nombreactividad', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'd_activity',
                'managed': False,
            },
        ),
    ]
